const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

let exifr;
try {
  exifr = require('exifr');
} catch (e) {
  console.error("Please install the 'exifr' package to run this script: npm install exifr --no-save");
  process.exit(1);
}

const RAW_DIR = path.join(__dirname, '../raw/curated_travel');
const ASSETS_DIR = path.join(__dirname, '../src/assets/images/travel');
const OUTPUT_FILE = path.join(__dirname, '../src/app/data/personal-data.ts');

async function processPhotos() {
  if (!fs.existsSync(RAW_DIR)) {
    console.log(`Directory ${RAW_DIR} does not exist. Please create it and add your curated photos.`);
    fs.mkdirSync(RAW_DIR, { recursive: true });
    return;
  }

  if (!fs.existsSync(ASSETS_DIR)) {
    fs.mkdirSync(ASSETS_DIR, { recursive: true });
  }

  const files = fs.readdirSync(RAW_DIR).filter(f => f.match(/\.(jpg|jpeg|png|heic)$/i));
  
  if (files.length === 0) {
    console.log(`No images found in ${RAW_DIR}. Add your curated photos to generate the timeline!`);
    return;
  }

  const entries = [];

  for (const file of files) {
    const rawPath = path.join(RAW_DIR, file);
    const destPath = path.join(ASSETS_DIR, file);

    console.log(`Processing: ${file}`);

    // Extract EXIF data
    let gps = null;
    let timestamp = Date.now();

    try {
      const exifData = await exifr.parse(rawPath);
      if (exifData) {
        if (exifData.latitude && exifData.longitude) {
          gps = { lat: exifData.latitude, lng: exifData.longitude };
        }
        if (exifData.DateTimeOriginal) {
          timestamp = new Date(exifData.DateTimeOriginal).getTime();
        }
      }
    } catch (e) {
      console.warn(`Could not extract EXIF for ${file}`);
    }

    // Copy file to assets so it gets bundled
    fs.copyFileSync(rawPath, destPath);

    // Default semantic location - can be enhanced with reverse geocoding API
    let semanticLocation = "Location Metadata Missing";
    if (gps) {
      semanticLocation = `Lat: ${gps.lat.toFixed(2)}, Lng: ${gps.lng.toFixed(2)}`;
    }

    entries.push({
      id: crypto.randomBytes(4).toString('hex'),
      timestamp: timestamp,
      semanticLocation: semanticLocation,
      coordinates: gps,
      photoPath: `assets/images/travel/${file}`
    });
  }

  // Generate TypeScript file
  const tsContent = `import { TravelEntry } from '../models/personal.model';\n\n// This file is auto-generated by the scripts/process-travel.js data fusion pipeline.\nexport const TRAVEL_DATA: TravelEntry[] = ${JSON.stringify(entries, null, 2)};\n`;

  fs.writeFileSync(OUTPUT_FILE, tsContent);
  console.log(`\nSuccessfully processed ${files.length} photos and generated ${OUTPUT_FILE}`);
}

processPhotos().catch(console.error);
